FROM  nvcr.io/nvidia/tritonserver:23.01-py3-sdk
LABEL maintainer="NVIDIA"
LABEL repository="tritonserver"

RUN apt-get update && apt-get install -y libsndfile1 openssh-server
RUN pip3 install soundfile
WORKDIR /workspace

RUN echo root:pwd2GPU|chpasswd
# 允许root用户使用密码通过ssh登录, 为了方便从远程ssh连接并调试docker环境
RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
RUN echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config
