FROM nvcr.io/nvidia/tritonserver:22.03-py3
LABEL maintainer="NVIDIA"
LABEL repository="tritonserver"

RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
RUN apt-get update && apt-get -y install swig && apt-get -y install python3-dev && apt-get install -y cmake
RUN pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple torch==1.11.0+cu113 \
    torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113
RUN pip3 install -v kaldifeat
RUN pip3 install pyyaml onnx
WORKDIR /workspace
RUN git clone https://github.com/Slyne/ctc_decoder.git && cd ctc_decoder/swig && bash setup.sh
COPY ./scripts scripts
